production build:
  stage:    build 
  script:
    - "export DEPLOY_TYPE=production && ./build.sh"
  only:
    - master
  tags:
    - my      
  cache:
    key: production
    paths:
        - node_modules/
        - dist/
production test:
  stage:      test
  script:     
    - pwd && echo passed
  only:
    - master 
  tags:
    - my


production deploy:
  stage: deploy
  script:
    - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/production/out"
    - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
    - docker build -t registry.becopay.com/ui/web:production-`git describe` .
    - docker push registry.becopay.com/ui/web:production-`git describe`
  environment:
    name: Production
    url: https://my.becopay.com/
  tags:
    - my           
  only:
    - master 
  cache:
    key: production
    paths:
        - dist/
    
sandbox build:
  stage: build
  only:
    - master 
  tags:
    - my          
  script:   
    - "export DEPLOY_TYPE=sandbox && ./build.sh"
  cache:
    key: sandbox
    paths:
        - node_modules/
        - dist/
        
sandbox test:
    stage:  test
    only:
        - master 
    tags:
        - my          
    script:     
        - pwd && echo passed

sandbox deploy:
  stage: deploy
  script:
    - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/sandbox/out"
    - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
    - docker build -t registry.becopay.com/ui/web:sandbox-`git describe` .
    - docker push registry.becopay.com/ui/web:sandbox-`git describe`
  environment:
    name: SandBox
    url: https://sandbox-my.becopay.com/
  tags:
    - my           
  only:
    - master
  cache:
    key: sandbox
    paths:
        - dist/  
                        
development build:
    stage:  build
    only:
        - develop 
    tags:
        - my          
    script: 
        - "export DEPLOY_TYPE=development && ./build.sh"
    cache:
        key: development
        paths:
            - node_modules/
            - dist/
        
development test:
    stage:      test
    only:
        - develop 
    tags:
        - my          
    script:     
        - pwd && echo passed 
        
development deploy:
    stage: deploy
    script:
        - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/development/out"
        - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
        - docker build -t registry.becopay.com/ui/web:staging-`git describe` .
        - docker push registry.becopay.com/ui/web:staging-`git describe`

    environment:
        name: Staging
        url: https://staging-my.becopay.com/
    tags:
        - my           
    only:
    - develop
    cache:
        key: development
        paths:
            - dist/

