prod build:
  stage:    build 
  script:
    - "export DEPLOY_TYPE=production && ./build.sh"
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  tags:
    - my      
  cache:
    key: production
    paths:
        - node_modules/
        - dist/
prod test:
  stage:      test
  script:     
    - pwd && echo passed
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/ 
  tags:
    - my


prod deploy:
  stage: deploy
  script:
    - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/production/out"
    - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
    - docker build -t registry.becopay.com/ui/web/production:`git describe` -t registry.becopay.com/ui/web/production:latest .
    - docker push registry.becopay.com/ui/web/production:`git describe`
    - docker push registry.becopay.com/ui/web/production:latest
  environment:
    name: Production
    url: https://my.becopay.com/
  tags:
    - my           
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/ 
  cache:
    key: production
    paths:
        - dist/
  artifacts:
    paths:
        - dist/
    
sandbox build:
  stage: build
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/ 
  tags:
    - my          
  script:   
    - "export DEPLOY_TYPE=sandbox && ./build.sh"
  cache:
    key: sandbox
    paths:
        - node_modules/
        - dist/
        
sandbox test:
    stage:  test
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/ 
    tags:
        - my          
    script:     
        - pwd && echo passed

sandbox deploy:
  stage: deploy
  script:
    - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/sandbox/out"
    - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
    - docker build -t registry.becopay.com/ui/web/sandbox:`git describe` -t registry.becopay.com/ui/web/sandbox:latest .
    - docker push registry.becopay.com/ui/web/sandbox:`git describe`
    - docker push registry.becopay.com/ui/web/sandbox:latest
  environment:
    name: SandBox
    url: https://sandbox-my.becopay.com/
  tags:
    - my           
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  cache:
    key: sandbox
    paths:
        - dist/
  artifacts:
    paths:
        - dist/  
                        
dev build:
    stage:  build
    only:
    - /^release/.*$/
    tags:
        - my          
    script: 
        - "export DEPLOY_TYPE=development && ./build.sh"
    cache:
        key: development
        paths:
            - node_modules/
            - dist/
        
dev test:
    stage:      test
    only:
    - /^release/.*$/
    tags:
        - my          
    script:     
        - pwd && echo passed 
        
dev deploy:
    stage: deploy
    script:
        - "rsync -r -a -v -e ssh --delete dist/ staging@79.137.5.196:/home/staging/my/development/out"
        - docker login -u Beygi  -p $CI_BUILD_TOKEN registry.becopay.com
        - docker build -t registry.becopay.com/ui/web/staging:`git describe` -t registry.becopay.com/ui/web/staging:latest .
        - docker push registry.becopay.com/ui/web/staging:`git describe`
        - docker push registry.becopay.com/ui/web/staging:latest

    environment:
        name: Staging
        url: https://staging-my.becopay.com/
    tags:
        - my           
    only:
    - /^release/.*$/
    cache:
        key: development
        paths:
            - dist/
    artifacts:
        paths:
            - dist/


